# Generated by Django 3.2.8 on 2021-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
