# Generated by Django 3.2.8 on 2021-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211101_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
