# Generated by Django 3.2.8 on 2021-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
