# Generated by Django 3.2.8 on 2022-01-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tag',
            field=models.CharField(choices=[('প্রোগ্রামিং বাসিক', 'রোগ্রামিং বাসিক'), ('নাম্বার থিওরি', 'নাম্বার থিওরি'), ('ডাটা স্ট্রাকচার', 'ডাটা স্ট্রাকচার'), ('ডাইনামিক প্রোগ্রামিং', 'ডাইনামিক প্রোগ্রামিং'), ('গ্রাফ থিওরি', 'গ্রাফ থিওরি')], max_length=100),
        ),
    ]
