# Generated by Django 3.2.8 on 2022-01-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20220101_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='content_short',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
