# Generated by Django 3.2.8 on 2022-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_tutorial_content_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content_short',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
