# Generated by Django 3.2.8 on 2022-01-02 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0015_recommendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Topic_Recommendation',
        ),
    ]
