# Generated by Django 3.2.8 on 2022-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_recommendation_topic_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic_recommendation',
            name='topic1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic_recommendation',
            name='topic2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
